file_format: "1"
id: anise60bn
name: Anise60BNav Rev. 1
type: shield
url: https://github.com/anisehid/anise60bn
requires: [anise_ctl]
features:
  - keys
  - underglow
siblings:
  - anise60bn_left
  - anise60bn_right
