#!/usr/bin/env python3
"""Generate ZMK Studio physical layouts (<shield>-layouts.dtsi) from AniseHID's
layout descriptions in anisehid/anise-kbd (desc-gen/desc/<name>.json).

Desc row tokens, in quarter keyunits: a positive number is a key of that width;
a negative number is the gap between the halves; a string "n" is an n-quarter
gap ("-1" is an end marker); "O" is the knob, drawn as a 1u key since its press
is a matrix key. Keys are emitted in row order, which is also the order of the
shield's matrix transform. Each row's key count is checked against the
transform, and a mismatch aborts rather than writing a layout that puts keys in
the wrong place.

Usage: PYTHONPATH=tools/pagegen python3 tools/make_layouts.py
"""
import collections
import json
import subprocess
from pathlib import Path

import parse

ROOT = Path(__file__).resolve().parent.parent
SHIELDS = ROOT / 'config' / 'boards' / 'shields'
Q = 25  # one quarter keyunit, in centi-keyunits

# shield -> desc file name in anisehid/anise-kbd
DESCS = {
    'anise60b': 'anise60b',
    'anise60bn': 'anise60bnav',
    'anise85a': 'anise85a',
    # anise85n is left out on purpose: its transform has 13 keys in the top and
    # bottom rows, its desc has 15 and 12. Someone with the board must decide
    # which one is right before it can get a layout.
}


def fetch(desc):
    raw = subprocess.check_output(
        ['gh', 'api', f'repos/anisehid/anise-kbd/contents/desc-gen/desc/{desc}.json',
         '-H', 'Accept: application/vnd.github.raw'])
    return json.loads(raw)['layout']


def keys(layout):
    out = []
    for y, row in enumerate(layout):
        x, keys_in_row = 0, []
        for i, t in enumerate(row):
            if t == 'O':
                keys_in_row.append((100, x, y * 100))
                x += 100
            elif isinstance(t, str):
                x += max(int(t), 0) * Q
            elif t < 0:
                x += -t * Q
            else:
                # The arrow cluster (float widths after a "0" marker) sits
                # 0.25u off the main block; this keeps every row flush right.
                if (isinstance(t, float) and row[i - 1] == '0'
                        and not any(isinstance(u, float) for u in row[:i])):
                    x += Q
                keys_in_row.append((int(t) * Q, x, y * 100))
                x += int(t) * Q
        out.append(keys_in_row)
    return out


def emit(shield, desc, rows):
    lines = ['#include <physical_layouts.dtsi>', '',
             '/*', f' * Generated by tools/make_layouts.py from anisehid/anise-kbd '
             f'desc-gen/desc/{desc}.json.',
             f' * Order matches default_transform in {shield}.dtsi.', ' */', '',
             '/ {', f'    {shield}_layout: {shield}_layout {{',
             '        compatible = "zmk,physical-layout";',
             f'        display-name = "Anise{shield[5:].upper()}";', '',
             '        keys  //                     w   h    x    y  rot  rx  ry']
    flat = [k for r in rows for k in r]
    for i, (w, x, y) in enumerate(flat):
        lines.append(f"            {'=' if i == 0 else ','} "
                     f"<&key_physical_attrs {w:3} 100 {x:4} {y:4}    0   0   0>")
    lines += ['            ;', '    };', '};', '']
    (SHIELDS / shield / f'{shield}-layouts.dtsi').write_text('\n'.join(lines))
    return len(flat)


def main():
    for shield, desc in DESCS.items():
        positions = parse.parse_shield(SHIELDS / shield)['positions']
        want = collections.Counter(r for r, _ in positions)
        rows = keys(fetch(desc))
        got = [len(r) for r in rows]
        exp = [want[i] for i in sorted(want)]
        if got != exp:
            raise SystemExit(f'{shield}: desc rows {got} != transform rows {exp}')
        print(f'{shield}: {emit(shield, desc, rows)} keys from {desc}.json')


if __name__ == '__main__':
    main()
